consul:  
   hostname: node1
   image: progrium/consul
   command: -server -bootstrap -advertise 172.17.42.1
   ports:
     - "8400:8400"
     - "8500:8500"
     - "8600:53/udp"
registrator:  
   image: gliderlabs/registrator
   command: consul://consul:8500
   hostname: registrator1
   volumes:
     - /var/run/docker.sock:/tmp/docker.sock
   links:
     - consul
