# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d13e12db9ede38f8365f7711837d7a0138c140ec0b1beadf7116830b4460bba4b2bacc37b089c2caa096766cc118a95fa71d3f9390b9f7059497d1a672812b07

test:
  secret_key_base: 4cce8a3085088ed192099078314880ec1f5b06c71b7d923d6182cff247db9d206affd65938b40337f63add74b44ef460fc882ca89302fc5bdc687f77d5be9a4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
